version: '3.5'
services:
  api:
    image: industrycare/boilerplate
    build:
      context: .
      dockerfile: conf/docker/Dockerfile
      target: development
    command: ['python', 'manage.py', 'runserver_plus', '0.0.0.0:8000']
    container_name: boilerplate_api
    volumes:
      - .:/code/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - postgres
      - mailhog
      - redis
      - celery

  celery:
    image: industrycare/boilerplate
    build:
      context: .
      dockerfile: conf/docker/Dockerfile
      target: development
    hostname: celery_service
    container_name: boilerplate_celery
    command: ['celery', '-A', 'project', 'worker', '--autoscale=10,5', '-l', 'INFO']
    volumes:
      - .:/code/app
    depends_on:
      - postgres
      - redis
    networks:
      - postgres
      - mailhog
      - redis
      - celery

  postgres:
    image: postgres:15-alpine
    container_name: boilerplate_db
    networks:
      - postgres
    volumes:
      - /tmp/local-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=boilerplate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: boilerplate_db-admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres
    volumes:
      - pgadmin_data:/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret

  mailhog:
    image: mailhog/mailhog
    container_name: boilerplate_mailhog
    networks:
      - mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:7-alpine
    container_name: boilerplate_redis
    networks:
      - redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data

  redis-ui:
    image: marian/rebrow
    container_name: boilerplate_redis-ui
    networks:
      - redis
    ports:
      - "5001:5001"

  flower:
    image: hugoseabra19/docker-celery-flower
    container_name: boilerplate_flower
    environment:
      # Redis DB used by celery
      - CELERY_BROKER_URL=redis://redis:6379/1
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    networks:
      - redis

networks:
  celery:
  postgres:
  mailhog:
  redis:

volumes:
  pgadmin_data:
  redis_data: