# Generated by Django 4.1.4 on 2022-12-29 15:16

import core.models.mixins.deletable_mixin
import core.models.mixins.domain_ruler_mixin
import core.models.mixins.entity_mixin
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Provide a name for the category', max_length=20, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
            bases=(core.models.mixins.entity_mixin.EntityMixin, core.models.mixins.domain_ruler_mixin.DomainRuleMixin, core.models.mixins.deletable_mixin.DeletableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Provide a name for the product', max_length=20, verbose_name='name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['category_id', 'name'],
            },
            bases=(core.models.mixins.entity_mixin.EntityMixin, core.models.mixins.domain_ruler_mixin.DomainRuleMixin, core.models.mixins.deletable_mixin.DeletableModelMixin, models.Model),
        ),
    ]
