# Generated by Django 4.1.4 on 2022-12-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Provide a name for the category', max_length=100, verbose_name='name'),
        ),
    ]
