name: 'Docker compose setup'
description: 'Installs docker-compose providing support to choose version'
author: hugoseabra19@gmail.com
branding:
  icon: 'grid'
  color: 'white'
inputs:
  docker-compose-version:
    description: 'Docker compose version'
    required: false
    default: '1.29.2'
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: ${{ inputs.docker-compose-version }}
