name: Boilerplate CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
    branches: [ "main" ]

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        max-parallel: 4
        matrix:
          python-version: ['3.10']

      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run services
        run: docker-compose up -d --build
      - name: Prepare environment variables
        run: docker exec api mv .env-sample .env
      - name: Check deployment
        run: docker exec api DEBUG=false python manage.py check --deploy
      - name: Run Tests
        run: docker exec api coverage run python manage.py test
      - name: Show coverage
        run: docker exec api coverage report
