name: Boilerplate CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        max-parallel: 4
        matrix:
          python-version: ['3.10']

      services:
        postgres:
          image: postgres:15-alpine
          env:
            POSTGRES_HOST: postgres
            POSTGRES_DB: db
            POSTGRES_PASSWORD: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
          ports:
            - 5432/tcp
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
      - name: Check
        run: |
          mv .env-sample .env
          DEBUG=false python manage.py check --deploy
      - name: Run Tests
        run: coverage run python manage.py test
      - name: Show coverage
        run: coverage report
